// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    [Migration("20251207162012_GetPersons_StoredProcedure")]
    partial class GetPersons_StoredProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryID = new Guid("c780c999-8945-480d-ab02-3c0d2c0836d6"),
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryID = new Guid("1f7294c7-940a-423d-b5c1-d09d8caf0c19"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryID = new Guid("4c83e5bb-df23-49d2-8d0a-e7616d336564"),
                            CountryName = "UK"
                        },
                        new
                        {
                            CountryID = new Guid("a4d39121-5788-4fa5-8e14-fe3781617862"),
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryID = new Guid("43d44ee4-0f3b-4a57-8aa3-fa7900494fa3"),
                            CountryName = "India"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.HasKey("PersonID");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = new Guid("37faf028-80b3-4471-8201-49b742e2f384"),
                            Address = "9367 Burrows Place",
                            CountryID = new Guid("c780c999-8945-480d-ab02-3c0d2c0836d6"),
                            DateOfBirth = new DateTime(2000, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kgilbart0@privacy.gov.au",
                            Gender = "Female",
                            PersonName = "Kate",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("b6478104-7ff7-4f12-a22a-657d77db5bff"),
                            Address = "62359 Veith Point",
                            CountryID = new Guid("1f7294c7-940a-423d-b5c1-d09d8caf0c19"),
                            DateOfBirth = new DateTime(1999, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lthickens1@nifty.com",
                            Gender = "Male",
                            PersonName = "Linoel",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("f47f89c5-98a4-48b3-b2d1-7909758578a7"),
                            Address = "948 Summer Ridge Circle",
                            CountryID = new Guid("4c83e5bb-df23-49d2-8d0a-e7616d336564"),
                            DateOfBirth = new DateTime(1990, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "skix2@fotki.com",
                            Gender = "Female",
                            PersonName = "Sonya",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("ea268eaa-b13a-4dee-8c20-79270ec7803e"),
                            Address = "5 Crowley Circle",
                            CountryID = new Guid("a4d39121-5788-4fa5-8e14-fe3781617862"),
                            DateOfBirth = new DateTime(1995, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "agumary3@hubpages.com",
                            Gender = "Female",
                            PersonName = "Agnella",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("eaf29c21-76f5-430d-b38f-c903d8c0fc1c"),
                            Address = "91217 Sycamore Circle",
                            CountryID = new Guid("43d44ee4-0f3b-4a57-8aa3-fa7900494fa3"),
                            DateOfBirth = new DateTime(1999, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cgrafton4@squarespace.com",
                            Gender = "Female",
                            PersonName = "Courtney",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("33f2c278-20e3-448a-a501-042f31571012"),
                            Address = "56945 Dennis Road",
                            CountryID = new Guid("43d44ee4-0f3b-4a57-8aa3-fa7900494fa3"),
                            DateOfBirth = new DateTime(1995, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dfrye5@epa.gov",
                            Gender = "Male",
                            PersonName = "Davey",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("66ec3051-1d0b-4434-9bc8-2ed833503f9b"),
                            Address = "86 Leroy Trail",
                            CountryID = new Guid("a4d39121-5788-4fa5-8e14-fe3781617862"),
                            DateOfBirth = new DateTime(1997, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elaxtonne6@ihg.com",
                            Gender = "Male",
                            PersonName = "Earl",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("59e3a9e6-07cd-4205-8b49-1a12418cef5f"),
                            Address = "7397 Elmside Parkway",
                            CountryID = new Guid("4c83e5bb-df23-49d2-8d0a-e7616d336564"),
                            DateOfBirth = new DateTime(1994, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ffrow7@marketwatch.com",
                            Gender = "Male",
                            PersonName = "Flinn",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("0b3b2afd-dd72-4656-930b-02696ae1809b"),
                            Address = "1 Cordelia Junction",
                            CountryID = new Guid("1f7294c7-940a-423d-b5c1-d09d8caf0c19"),
                            DateOfBirth = new DateTime(1994, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "efroome8@yandex.ru",
                            Gender = "Female",
                            PersonName = "Elyssa",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("7601b84c-5187-45fb-9090-59e44fced8a9"),
                            Address = "5 Rowland Parkway",
                            CountryID = new Guid("c780c999-8945-480d-ab02-3c0d2c0836d6"),
                            DateOfBirth = new DateTime(1994, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ewandena@reddit.com",
                            Gender = "Female",
                            PersonName = "Ettie",
                            ReceiveNewsLetters = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
